apiVersion: v1
kind: Service
metadata:
  name: django-deployment
  namespace: default
spec:
  ports:
  - nodePort: 30412
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-deployment
  type: NodePort