# Generated by Django 3.2.8 on 2021-10-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fs_file',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
